### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by pguerin3** [automatiko-io/docs-automatiko.github.io#1]
Just noticed in your GettingStartedPage:
`
 https://github.com/automatiko-io/docs-automatiko.github.io/blob/main/main/0.21.0/getting-started-code.html
`

There is a mistake in the link as follows:
`
https://github.com/automatiko-io/automatiko-examples/workflows-java-dsl
`

Should be:
`
https://github.com/automatiko-io/automatiko-examples/tree/main/workflows-java-dsl
`

**Comment by mswiderski** [comment]
thanks for let me know about that, just fixed it here https://github.com/automatiko-io/automatiko-engine/commit/c5773ffade551975dc056798258ff3aa66b5b8fc

will be out on the website within several minutes
